Repository croct-tech/templates, pull requests merged in 2025-04, with the labels that each got.

#1 Add templates for Next 13, 14 and 15
  templates/croct/utils/example-launcher/template.json5
  templates/magicui/ui/marquee/configuration/marquee-component.json
  templates/nextjs/croct/asset/file.svg
  templates/nextjs/croct/asset/globe.svg
  templates/nextjs/croct/asset/next.svg
  templates/nextjs/croct/asset/vercel.svg
  templates/nextjs/croct/asset/window.svg
  templates/nextjs/croct/code/lib/markdown.js
  templates/nextjs/croct/code/lib/markdown.tsx
  templates/nextjs/croct/code/page/13/css/index.js
  templates/nextjs/croct/code/page/13/css/index.tsx
  templates/nextjs/croct/code/page/13/css/page.js
  templates/nextjs/croct/code/page/13/tailwind/index.js
  templates/nextjs/croct/code/page/13/tailwind/index.tsx
  templates/nextjs/croct/code/page/13/tailwind/page.js
  templates/nextjs/croct/code/page/14/css/index.js
  templates/nextjs/croct/code/page/14/css/index.tsx
  templates/nextjs/croct/code/page/14/css/page.js
  templates/nextjs/croct/code/page/14/tailwind/index.js
  templates/nextjs/croct/code/page/14/tailwind/index.tsx
  templates/nextjs/croct/code/page/14/tailwind/page.js
  templates/nextjs/croct/code/page/15/css/index.tsx
  templates/nextjs/croct/code/page/15/css/page.js
  templates/nextjs/croct/code/page/15/tailwind/index.tsx
  templates/nextjs/croct/code/page/15/tailwind/page.js
  templates/nextjs/croct/configuration/13/next-homepage-content.en.json
  templates/nextjs/croct/configuration/13/next-starter-page-schema.json
  templates/nextjs/croct/configuration/14/next-homepage-content.en.json
  templates/nextjs/croct/configuration/14/next-starter-page-schema.json
  templates/nextjs/croct/configuration/15/next-homepage-content.en.json
  templates/nextjs/croct/configuration/15/next-starter-page-schema.json
  templates/nextjs/croct/template.json5
  templates/nextjs/project/template.json5
  templates/shadcn/croct/template.json5
  templates/shadcn/integration/template.json5
  templates/shadcn/ui/block/pricing-page/configuration/plan-card-component.json
  templates/shadcn/ui/block/pricing-page/configuration/pricing-section-component.json
  templates/shadcn/ui/block/pricing-page/template.json5
  templates/shadcn/ui/slot/template.json5
Labels: feature

#4 Refactor pricing plan template
  templates/magicui/ui/marquee/code/nextjs/page.tsx
  templates/magicui/ui/marquee/code/react/example.tsx
  templates/nextjs/croct/code/page/13/css/index.js
  templates/nextjs/croct/code/page/13/css/index.tsx
  templates/nextjs/croct/code/page/13/css/page.js
  templates/nextjs/croct/code/page/13/tailwind/index.js
  templates/nextjs/croct/code/page/13/tailwind/index.tsx
  templates/nextjs/croct/code/page/13/tailwind/page.js
  templates/nextjs/croct/code/page/14/css/index.js
  templates/nextjs/croct/code/page/14/css/index.tsx
  templates/nextjs/croct/code/page/14/css/page.js
  templates/nextjs/croct/code/page/14/tailwind/index.js
  templates/nextjs/croct/code/page/14/tailwind/index.tsx
  templates/nextjs/croct/code/page/14/tailwind/page.js
  templates/nextjs/croct/code/page/15/css/index.js
  templates/nextjs/croct/code/page/15/css/index.tsx
  templates/nextjs/croct/code/page/15/css/page.js
  templates/nextjs/croct/code/page/15/tailwind/index.js
  templates/nextjs/croct/code/page/15/tailwind/index.tsx
  templates/nextjs/croct/code/page/15/tailwind/page.js
  templates/nextjs/croct/template.json5
  templates/shadcn/project/template.json5
  templates/shadcn/ui/block/pricing-page/code/page.tsx
  templates/shadcn/ui/block/pricing-page/code/plan-card.tsx
  templates/shadcn/ui/block/pricing-page/template.json5
  templates/shadcn/ui/slot/template.json5
Labels: enhancement

#5 Recreate marquee example
  templates/magicui/ui/component/template.json5
  templates/magicui/ui/marquee/code/components/review-card.tsx
  templates/magicui/ui/marquee/code/components/review-list.tsx
  templates/magicui/ui/marquee/code/nextjs/page.tsx
  templates/magicui/ui/marquee/code/page/nextjs/index.tsx
  templates/magicui/ui/marquee/code/page/nextjs/page.tsx
  templates/magicui/ui/marquee/code/page/react/page.tsx
  templates/magicui/ui/marquee/code/react/example.tsx
  templates/magicui/ui/marquee/configuration/marquee-component.json
  templates/magicui/ui/marquee/configuration/marquee-content.en.json
  templates/magicui/ui/marquee/configuration/marquee-schema.json
  templates/magicui/ui/marquee/template.json5
  templates/shadcn/integration/template.json5
  templates/shadcn/project/template.json5
  templates/shadcn/ui/block/pricing-page/template.json5
  templates/shadcn/ui/slot/template.json5
Labels: feature

#7 Fix logic to detect app router
  templates/magicui/ui/component/template.json5
Labels: bug

#12 Add template for Magic UI tweet card
  templates/magicui/ui/component/template.json5
  templates/magicui/ui/tweet-card/code/components/client/tweet.tsx
  templates/magicui/ui/tweet-card/code/components/server/tweet.tsx
  templates/magicui/ui/tweet-card/code/page/nextjs/index.tsx
  templates/magicui/ui/tweet-card/code/page/nextjs/page.tsx
  templates/magicui/ui/tweet-card/code/page/react/page.tsx
  templates/magicui/ui/tweet-card/configuration/tweet-card-content.en.json
  templates/magicui/ui/tweet-card/configuration/tweet-card-schema.json
  templates/magicui/ui/tweet-card/template.json5
Labels: feature

#15 Add template for Magic UI avatar circles
  templates/magicui/ui/avatar-circles/code/components/avatar-stack.tsx
  templates/magicui/ui/avatar-circles/code/page/nextjs/index.tsx
  templates/magicui/ui/avatar-circles/code/page/nextjs/page.tsx
  templates/magicui/ui/avatar-circles/code/page/react/page.tsx
  templates/magicui/ui/avatar-circles/configuration/avatar-circles-content.en.json
  templates/magicui/ui/avatar-circles/configuration/avatar-circles-schema.json
  templates/magicui/ui/avatar-circles/template.json5
Labels: feature

#16 Add template for Magic UI icon cloud
  templates/magicui/ui/icon-cloud/code/components/icon-cloud-demo.tsx
  templates/magicui/ui/icon-cloud/code/page/nextjs/index.tsx
  templates/magicui/ui/icon-cloud/code/page/nextjs/page.tsx
  templates/magicui/ui/icon-cloud/code/page/react/page.tsx
  templates/magicui/ui/icon-cloud/configuration/icon-cloud-content.en.json
  templates/magicui/ui/icon-cloud/configuration/icon-cloud-schema.json
  templates/magicui/ui/icon-cloud/template.json5
Labels: feature

#17 Add template for Magic UI lens
  templates/magicui/ui/lens/code/components/lens-card.tsx
  templates/magicui/ui/lens/code/page/nextjs/index.tsx
  templates/magicui/ui/lens/code/page/nextjs/page.tsx
  templates/magicui/ui/lens/code/page/react/page.tsx
  templates/magicui/ui/lens/configuration/lens-content.en.json
  templates/magicui/ui/lens/configuration/lens-schema.json
  templates/magicui/ui/lens/template.json5
Labels: feature

#18 Add template for Magic UI script copy btn
  templates/magicui/ui/script-copy-btn/code/components/copy-command-block.tsx
  templates/magicui/ui/script-copy-btn/code/page/nextjs/index.tsx
  templates/magicui/ui/script-copy-btn/code/page/nextjs/page.tsx
  templates/magicui/ui/script-copy-btn/code/page/react/page.tsx
  templates/magicui/ui/script-copy-btn/configuration/script-copy-btn-content.en.json
  templates/magicui/ui/script-copy-btn/configuration/script-copy-btn-schema.json
  templates/magicui/ui/script-copy-btn/template.json5
Labels: feature

#23 Update metadata and remove shadcn-ui/integration
  templates/croct/utils/example-launcher/template.json5
  templates/croct/utils/filename-generator/template.json5
  templates/magic-ui/ui/animated-list/template.json5
  templates/magic-ui/ui/avatar-circles/cover.png
  templates/magic-ui/ui/avatar-circles/template.json5
  templates/magic-ui/ui/bento-grid/template.json5
  templates/magic-ui/ui/code-comparison/template.json5
  templates/magic-ui/ui/component/template.json5
  templates/magic-ui/ui/dock/template.json5
  templates/magic-ui/ui/globe/template.json5
  templates/magic-ui/ui/hero-video-dialog/template.json5
  templates/magic-ui/ui/icon-cloud/template.json5
  templates/magic-ui/ui/lens/template.json5
  templates/magic-ui/ui/marquee/template.json5
  templates/magic-ui/ui/orbiting-circles/template.json5
  templates/magic-ui/ui/script-copy-btn/template.json5
  templates/magic-ui/ui/terminal/template.json5
  templates/magic-ui/ui/tweet-card/template.json5
  templates/nextjs/croct/template.json5
  templates/nextjs/project/template.json5
  templates/shadcn-ui/croct/README.md
  templates/shadcn-ui/croct/template.json5
  templates/shadcn-ui/integration/README.md
  templates/shadcn-ui/integration/template.json5
  templates/shadcn-ui/project/template.json5
  templates/shadcn-ui/ui/block/pricing-page/template.json5
  templates/shadcn-ui/ui/component/template.json5
Labels: maintenance

#22 Add template covers
  templates/croct/utils/example-launcher/cover.png
  templates/croct/utils/filename-generator/cover.png
  templates/nextjs/croct/cover.png
  templates/shadcn-ui/croct/cover.png
Labels: documentation

#24 Add covers
  templates/magic-ui/ui/component/cover.png
  templates/nextjs/project/cover.png
  templates/shadcn-ui/project/cover.png
  templates/shadcn-ui/ui/component/cover.png
Labels: documentation

#26 Add workflow for publishing templates
  .eslintrc.cjs
  .github/workflows/check-required-labels.yaml
  .github/workflows/publish-templates.yaml
  .github/workflows/validate-templates.yaml
  .gitignore
  assets/icons/technology/ariakit.png
  assets/icons/technology/framer-motion.png
  assets/icons/technology/html.png
  assets/icons/technology/javascript.png
  assets/icons/technology/magic-ui.png
  assets/icons/technology/material-ui.png
  assets/icons/technology/nextjs.png
  assets/icons/technology/react.png
  assets/icons/technology/shadcn-ui.png
  assets/icons/technology/shiki.png
  assets/icons/technology/tailwind-css.png
  assets/icons/technology/typescript.png
  bin/template.ts
  package-lock.json
  package.json
  templates/croct/utils/example-launcher/template.json5
  templates/croct/utils/filename-generator/template.json5
  templates/magic-ui/ui/animated-list/template.json5
  templates/magic-ui/ui/avatar-circles/template.json5
  templates/magic-ui/ui/bento-grid/template.json5
  templates/magic-ui/ui/code-comparison/template.json5
  templates/magic-ui/ui/component/template.json5
  templates/magic-ui/ui/dock/template.json5
  templates/magic-ui/ui/globe/template.json5
  templates/magic-ui/ui/hero-video-dialog/template.json5
  templates/magic-ui/ui/icon-cloud/template.json5
  templates/magic-ui/ui/lens/template.json5
  templates/magic-ui/ui/marquee/template.json5
  templates/magic-ui/ui/orbiting-circles/template.json5
  templates/magic-ui/ui/script-copy-btn/template.json5
  templates/magic-ui/ui/terminal/template.json5
  templates/magic-ui/ui/tweet-card/template.json5
  templates/nextjs/croct/template.json5
  templates/nextjs/project/template.json5
  templates/shadcn-ui/croct/template.json5
  templates/shadcn-ui/project/template.json5
  templates/shadcn-ui/ui/block/pricing-page/template.json5
  templates/shadcn-ui/ui/component/template.json5
  tsconfig.json
Labels: feature

#27 Fix validation
  bin/template.ts
Labels: bug

#28 Improve workflow
  .github/workflows/publish-templates.yaml
  bin/template.ts
  package-lock.json
  package.json
Labels: enhancement

#29 Add verified flag to verified templates
  templates/croct/experience/e-commerce/cart/template.json5
  templates/croct/experience/e-commerce/instagram-campaign/template.json5
  templates/croct/experience/e-commerce/interest/template.json5
  templates/croct/experience/e-commerce/landing-page/template.json5
  templates/croct/experience/e-commerce/location/template.json5
  templates/croct/experience/e-commerce/marketing-campaign/template.json5
  templates/croct/experience/e-commerce/search-campaign/template.json5
  templates/croct/experience/saas/abm-campaign/template.json5
  templates/croct/experience/saas/customer/template.json5
  templates/croct/experience/saas/interest/template.json5
  templates/croct/experience/saas/landing-page/template.json5
  templates/croct/experience/saas/linkedin-campaign/template.json5
  templates/croct/experience/saas/marketing-campaign/template.json5
  templates/croct/experience/saas/search-campaign/template.json5
  templates/croct/experiment/all-users/template.json5
  templates/croct/experiment/segmented/template.json5
  templates/croct/utils/example-launcher/template.json5
  templates/croct/utils/filename-generator/template.json5
  templates/nextjs/croct/template.json5
  templates/shadcn-ui/croct/template.json5
Labels: maintenance

#30 Fix summary counters
  bin/template.ts
Labels: bug

#32 Add some fixes to the use case templates
  templates/croct/experience/e-commerce/cart/README.md
  templates/croct/experience/e-commerce/cart/template.json5
  templates/croct/experience/e-commerce/instagram-campaign/README.md
  templates/croct/experience/e-commerce/instagram-campaign/template.json5
  templates/croct/experience/e-commerce/interest/README.md
  templates/croct/experience/e-commerce/landing-page/README.md
  templates/croct/experience/e-commerce/location/README.md
  templates/croct/experience/e-commerce/marketing-campaign/README.md
  templates/croct/experience/e-commerce/marketing-campaign/template.json5
  templates/croct/experience/e-commerce/search-campaign/README.md
  templates/croct/experience/e-commerce/search-campaign/template.json5
  templates/croct/experience/saas/abm-campaign/README.md
  templates/croct/experience/saas/abm-campaign/template.json5
  templates/croct/experience/saas/customer/README.md
  templates/croct/experience/saas/customer/template.json5
  templates/croct/experience/saas/interest/README.md
  templates/croct/experience/saas/landing-page/README.md
  templates/croct/experience/saas/linkedin-campaign/README.md
  templates/croct/experience/saas/linkedin-campaign/template.json5
  templates/croct/experience/saas/marketing-campaign/README.md
  templates/croct/experience/saas/marketing-campaign/template.json5
  templates/croct/experience/saas/search-campaign/README.md
  templates/croct/experience/saas/search-campaign/template.json5
  templates/croct/experiment/all-users/README.md
  templates/croct/experiment/segmented/README.md
Labels: maintenance

#33 Update covers
  templates/croct/utils/example-launcher/cover.png
  templates/croct/utils/filename-generator/cover.png
  templates/magic-ui/ui/animated-list/cover.png
  templates/magic-ui/ui/animated-list/template.json5
  templates/magic-ui/ui/avatar-circles/cover.png
  templates/magic-ui/ui/avatar-circles/template.json5
  templates/magic-ui/ui/bento-grid/cover.png
  templates/magic-ui/ui/bento-grid/template.json5
  templates/magic-ui/ui/code-comparison/cover.png
  templates/magic-ui/ui/code-comparison/template.json5
  templates/magic-ui/ui/component/cover.png
  templates/magic-ui/ui/dock/cover.png
  templates/magic-ui/ui/dock/template.json5
  templates/magic-ui/ui/globe/cover.png
  templates/magic-ui/ui/globe/template.json5
  templates/magic-ui/ui/hero-video-dialog/cover.png
  templates/magic-ui/ui/hero-video-dialog/template.json5
  templates/magic-ui/ui/icon-cloud/cover.png
  templates/magic-ui/ui/icon-cloud/template.json5
  templates/magic-ui/ui/lens/cover.png
  templates/magic-ui/ui/lens/template.json5
  templates/magic-ui/ui/marquee/cover.png
  templates/magic-ui/ui/marquee/template.json5
  templates/magic-ui/ui/orbiting-circles/cover.png
  templates/magic-ui/ui/orbiting-circles/template.json5
  templates/magic-ui/ui/script-copy-btn/cover.png
  templates/magic-ui/ui/script-copy-btn/template.json5
  templates/magic-ui/ui/terminal/cover.png
  templates/magic-ui/ui/terminal/template.json5
  templates/magic-ui/ui/tweet-card/cover.png
  templates/magic-ui/ui/tweet-card/template.json5
  templates/nextjs/croct/cover.png
  templates/nextjs/project/cover.png
  templates/shadcn-ui/croct/cover.png
  templates/shadcn-ui/project/cover.png
  templates/shadcn-ui/ui/block/pricing-page/cover.png
  templates/shadcn-ui/ui/component/cover.png
Labels: enhancement

#35 Fix templates issues
  templates/nextjs/croct/template.json5
  templates/shadcn-ui/ui/block/pricing-page/template.json5
Labels: bug

#38 Fix template directory logic
  templates/shadcn-ui/croct/template.json5
  templates/shadcn-ui/project/template.json5
Labels: bug

#37 Fix template issues
  templates/croct/experience/e-commerce/cart/configuration/home-carousel-experience-content.en.json
  templates/croct/experience/e-commerce/instagram-campaign/template.json5
Labels: bug

#40 Update callout to use new style
  templates/shadcn-ui/ui/component/README.md
Labels: enhancement

#41 Add utility categories
  templates/magic-ui/ui/component/template.json5
  templates/shadcn-ui/ui/component/template.json5
Labels: enhancement

#44 Change templates cli command name
  templates/croct/experience/e-commerce/cart/README.md
  templates/croct/experience/e-commerce/instagram-campaign/README.md
  templates/croct/experience/e-commerce/interest/README.md
  templates/croct/experience/e-commerce/landing-page/README.md
  templates/croct/experience/e-commerce/location/README.md
  templates/croct/experience/e-commerce/marketing-campaign/README.md
  templates/croct/experience/e-commerce/search-campaign/README.md
  templates/croct/experience/saas/abm-campaign/README.md
  templates/croct/experience/saas/customer/README.md
  templates/croct/experience/saas/interest/README.md
  templates/croct/experience/saas/landing-page/README.md
  templates/croct/experience/saas/linkedin-campaign/README.md
  templates/croct/experience/saas/marketing-campaign/README.md
  templates/croct/experience/saas/search-campaign/README.md
  templates/croct/experiment/all-users/README.md
  templates/croct/experiment/segmented/README.md
  templates/croct/ui/block/announcement-bar/README.md
  templates/croct/ui/block/card-section/README.md
  templates/croct/ui/block/carousel-section/README.md
  templates/croct/ui/block/faq-section/README.md
  templates/croct/ui/block/hero-section/README.md
  templates/croct/ui/block/logo-cloud/README.md
  templates/croct/ui/block/product-cards-section/README.md
  templates/croct/ui/block/testimonial-section/README.md
  templates/croct/ui/component/callout/README.md
  templates/croct/ui/component/demo-request-form/README.md
  templates/croct/ui/component/image-comparison-slider/README.md
  templates/croct/ui/component/modal-dialog/README.md
  templates/croct/ui/component/navbar/README.md
  templates/croct/ui/component/newsletter-form/README.md
  templates/croct/ui/component/video-player/README.md
  templates/magic-ui/ui/animated-list/README.md
  templates/magic-ui/ui/avatar-circles/README.md
  templates/magic-ui/ui/bento-grid/README.md
  templates/magic-ui/ui/code-comparison/README.md
  templates/magic-ui/ui/dock/README.md
  templates/magic-ui/ui/globe/README.md
  templates/magic-ui/ui/hero-video-dialog/README.md
  templates/magic-ui/ui/icon-cloud/README.md
  templates/magic-ui/ui/lens/README.md
  templates/magic-ui/ui/marquee/README.md
  templates/magic-ui/ui/orbiting-circles/README.md
  templates/magic-ui/ui/script-copy-btn/README.md
  templates/magic-ui/ui/terminal/README.md
  templates/magic-ui/ui/tweet-card/README.md
  templates/nextjs/croct/README.md
  templates/nextjs/project/README.md
  templates/shadcn-ui/croct/README.md
  templates/shadcn-ui/project/README.md
  templates/shadcn-ui/ui/block/pricing-page/README.md
Labels: maintenance

#45 Fix templates
  templates/croct/experience/saas/interest/README.md
  templates/croct/ui/block/cards-section/README.md
  templates/croct/ui/block/cards-section/configuration/cards-section-content.en.json
  templates/croct/ui/block/cards-section/configuration/content-cards-schema.json
  templates/croct/ui/block/cards-section/configuration/cta-schema.json
  templates/croct/ui/block/cards-section/cover.png
  templates/croct/ui/block/cards-section/template.json5
  templates/croct/ui/block/carousel-section/README.md
  templates/croct/ui/component/demo-request-form/README.md
Labels: bug

#46 Fix templates installationUrl
  templates/croct/experience/e-commerce/cart/template.json5
  templates/croct/experience/e-commerce/instagram-campaign/template.json5
  templates/croct/experience/e-commerce/interest/template.json5
  templates/croct/experience/e-commerce/landing-page/template.json5
  templates/croct/experience/e-commerce/location/template.json5
  templates/croct/experience/e-commerce/marketing-campaign/template.json5
  templates/croct/experience/e-commerce/search-campaign/template.json5
  templates/croct/experience/saas/abm-campaign/template.json5
  templates/croct/experience/saas/customer/template.json5
  templates/croct/experience/saas/interest/template.json5
  templates/croct/experience/saas/landing-page/template.json5
  templates/croct/experience/saas/linkedin-campaign/template.json5
  templates/croct/experience/saas/marketing-campaign/template.json5
  templates/croct/experience/saas/search-campaign/template.json5
  templates/croct/experiment/all-users/template.json5
  templates/croct/experiment/segmented/template.json5
  templates/croct/ui/block/announcement-bar/template.json5
  templates/croct/ui/block/cards-section/template.json5
  templates/croct/ui/block/carousel-section/template.json5
  templates/croct/ui/block/faq-section/template.json5
  templates/croct/ui/block/hero-section/template.json5
  templates/croct/ui/block/logo-cloud/template.json5
  templates/croct/ui/block/product-cards-section/template.json5
  templates/croct/ui/block/testimonial-section/template.json5
  templates/croct/ui/component/callout/template.json5
  templates/croct/ui/component/demo-request-form/template.json5
  templates/croct/ui/component/image-comparison-slider/template.json5
  templates/croct/ui/component/modal-dialog/template.json5
  templates/croct/ui/component/navbar/template.json5
  templates/croct/ui/component/newsletter-form/template.json5
  templates/croct/ui/component/video-player/template.json5
Labels: bug

#47 Update cover of use case templates
  templates/croct/experience/e-commerce/cart/cover.png
  templates/croct/experience/e-commerce/instagram-campaign/cover.png
  templates/croct/experience/e-commerce/interest/cover.png
  templates/croct/experience/e-commerce/landing-page/cover.png
  templates/croct/experience/e-commerce/location/cover.png
  templates/croct/experience/e-commerce/marketing-campaign/cover.png
  templates/croct/experience/e-commerce/search-campaign/cover.png
  templates/croct/experience/saas/abm-campaign/cover.png
  templates/croct/experience/saas/customer/cover.png
  templates/croct/experience/saas/interest/cover.png
  templates/croct/experience/saas/landing-page/cover.png
  templates/croct/experience/saas/linkedin-campaign/cover.png
  templates/croct/experience/saas/marketing-campaign/cover.png
  templates/croct/experience/saas/search-campaign/cover.png
  templates/croct/experiment/all-users/cover.png
  templates/croct/experiment/segmented/cover.png
Labels: maintenance
