Repository croct-tech/templates, pull requests merged in 2025-06, with the labels that each got.

#109 Fix Croct Cmd commands
  templates/croct/integration/sanity/README.md
  templates/material-ui/block/pricing-section/README.md
Labels: maintenance

#113 Add Mantine templates
  assets/icons/technology/mantine.png
  bin/cli.ts
  templates/mantine/block/cards-carousel/README.md
  templates/mantine/block/cards-carousel/cover.png
  templates/mantine/block/cards-carousel/template.json5
  templates/mantine/block/faq-simple/README.md
  templates/mantine/block/faq-simple/cover.png
  templates/mantine/block/faq-simple/template.json5
  templates/mantine/block/features-asymmetrical/README.md
  templates/mantine/block/features-asymmetrical/cover.png
  templates/mantine/block/features-asymmetrical/template.json5
  templates/mantine/block/features-cards/README.md
  templates/mantine/block/features-cards/cover.png
  templates/mantine/block/features-cards/template.json5
  templates/mantine/block/hero-bullets/README.md
  templates/mantine/block/hero-bullets/cover.png
  templates/mantine/block/hero-bullets/template.json5
  templates/mantine/block/hero-content-left/README.md
  templates/mantine/block/hero-content-left/cover.png
  templates/mantine/block/hero-content-left/template.json5
  templates/mantine/block/stats-group/README.md
  templates/mantine/block/stats-group/cover.png
  templates/mantine/block/stats-group/template.json5
  templates/mantine/component/carousel-card/README.md
  templates/mantine/component/carousel-card/cover.png
  templates/mantine/component/carousel-card/template.json5
  templates/mantine/component/comment-html/README.md
  templates/mantine/component/comment-html/cover.png
  templates/mantine/component/comment-html/template.json5
  templates/mantine/component/cookies-banner/README.md
  templates/mantine/component/cookies-banner/cover.png
  templates/mantine/component/cookies-banner/template.json5
  templates/mantine/component/email-banner/README.md
  templates/mantine/component/email-banner/cover.png
  templates/mantine/component/email-banner/template.json5
  templates/mantine/component/header-menu/README.md
  templates/mantine/component/header-menu/cover.png
  templates/mantine/component/header-menu/template.json5
  templates/mantine/component/header-simple/README.md
  templates/mantine/component/header-simple/cover.png
  templates/mantine/component/header-simple/template.json5
  templates/mantine/component/image-action-banner/README.md
  templates/mantine/component/image-action-banner/cover.png
  templates/mantine/component/image-action-banner/template.json5
  templates/registry.json5
Labels: feature

#118 Update package command
  templates/croct/integration/sanity/template.json5
  templates/croct/starter/nextjs/template.json5
  templates/croct/starter/shadcn-ui/template.json5
  templates/shadcn-ui/component/template.json5
Labels: maintenance

#119 Improve Sanity template
  templates/croct/integration/sanity/template.json5
Labels: enhancement

#120 Sanity templates
  templates/croct/integration/sanity-ab-testing/README.md
  templates/croct/integration/sanity-ab-testing/intro-illustration.png
  templates/croct/integration/sanity-personalization/README.md
  templates/croct/integration/sanity-personalization/intro-illustration.png
Labels: maintenance

#116 Add integration template for Strapi
  templates/croct/integration/strapi/README.md
  templates/croct/integration/strapi/code/page.tsx
  templates/croct/integration/strapi/configuration/dynamic-zone-map-schema.json
  templates/croct/integration/strapi/configuration/hero-section-schema.json
  templates/croct/integration/strapi/configuration/home-dynamic-zones-content.json
  templates/croct/integration/strapi/configuration/home-hero-content.en.json
  templates/croct/integration/strapi/intro-illustration-1.png
  templates/croct/integration/strapi/intro-illustration-2.png
  templates/croct/integration/strapi/template.json5
Labels: feature

#124 Add sign-up side template from Material UI
  templates/croct/ui/component/demo-request-form/template.json5
  templates/material-ui/block/sign-up-side/README.md
  templates/material-ui/block/sign-up-side/code/components/Content.tsx
  templates/material-ui/block/sign-up-side/code/components/CustomIcons.tsx
  templates/material-ui/block/sign-up-side/code/components/SignUpCard.tsx
  templates/material-ui/block/sign-up-side/code/components/SignUpSection.tsx
  templates/material-ui/block/sign-up-side/code/page/nextjs/index.tsx
  templates/material-ui/block/sign-up-side/code/page/nextjs/page.tsx
  templates/material-ui/block/sign-up-side/code/page/react/page.tsx
  templates/material-ui/block/sign-up-side/configuration/bullet-list-content-schema.json
  templates/material-ui/block/sign-up-side/configuration/sign-up-side-content.en.json
  templates/material-ui/block/sign-up-side/cover.png
  templates/material-ui/block/sign-up-side/extension.json5
  templates/material-ui/block/sign-up-side/template.json5
  templates/npm/react-phone-number-input/template.json5
Labels: feature

#126 Add Mantine image action banner template
  templates/croct/ui/component/modal-dialog/template.json5
  templates/mantine/component/image-action-banner/README.md
  templates/mantine/component/image-action-banner/code/components/ImageActionBanner/index.module.css
  templates/mantine/component/image-action-banner/code/components/ImageActionBanner/index.tsx
  templates/mantine/component/image-action-banner/code/page/nextjs/index.tsx
  templates/mantine/component/image-action-banner/code/page/nextjs/page.tsx
  templates/mantine/component/image-action-banner/code/page/react/page.tsx
  templates/mantine/component/image-action-banner/code/utils/markdown.tsx
  templates/mantine/component/image-action-banner/configuration/image-action-banner-content.en.json
  templates/mantine/component/image-action-banner/configuration/image-action-banner-schema.json
  templates/mantine/component/image-action-banner/extension.json5
  templates/mantine/component/image-action-banner/template.json5
Labels: feature

#130 Add Mantine stats group template
  templates/mantine/block/stats-group/README.md
  templates/mantine/block/stats-group/code/components/StatsGroup/index.module.css
  templates/mantine/block/stats-group/code/components/StatsGroup/index.tsx
  templates/mantine/block/stats-group/code/page/nextjs/index.tsx
  templates/mantine/block/stats-group/code/page/nextjs/page.tsx
  templates/mantine/block/stats-group/code/page/react/page.tsx
  templates/mantine/block/stats-group/configuration/stats-group-content.en.json
  templates/mantine/block/stats-group/configuration/stats-group-schema.json
  templates/mantine/block/stats-group/extension.json5
  templates/mantine/block/stats-group/template.json5
Labels: feature

#128 Add Mantine cookies banner template
  templates/hero-ui/component/cookie-consent/template.json5
  templates/mantine/component/cookies-banner/README.md
  templates/mantine/component/cookies-banner/code/components/CookiesBanner/index.module.css
  templates/mantine/component/cookies-banner/code/components/CookiesBanner/index.tsx
  templates/mantine/component/cookies-banner/code/page/nextjs/index.tsx
  templates/mantine/component/cookies-banner/code/page/nextjs/page.tsx
  templates/mantine/component/cookies-banner/code/page/react/page.tsx
  templates/mantine/component/cookies-banner/code/utils/markdown.tsx
  templates/mantine/component/cookies-banner/configuration/cookies-banner-content.en.json
  templates/mantine/component/cookies-banner/configuration/cookies-banner-schema.json
  templates/mantine/component/cookies-banner/extension.json5
  templates/mantine/component/cookies-banner/template.json5
Labels: feature

#132 Add Mantine Faq section template
  templates/croct/ui/block/faq-section/template.json5
  templates/mantine/block/faq-simple/README.md
  templates/mantine/block/faq-simple/code/components/FaqSimple/index.module.css
  templates/mantine/block/faq-simple/code/components/FaqSimple/index.tsx
  templates/mantine/block/faq-simple/code/page/nextjs/index.tsx
  templates/mantine/block/faq-simple/code/page/nextjs/page.tsx
  templates/mantine/block/faq-simple/code/page/react/page.tsx
  templates/mantine/block/faq-simple/code/utils/markdown.tsx
  templates/mantine/block/faq-simple/configuration/faq-section-content.en.json
  templates/mantine/block/faq-simple/configuration/faq-section-schema.json
  templates/mantine/block/faq-simple/extension.json5
  templates/mantine/block/faq-simple/template.json5
  templates/material-ui/block/faq-section/template.json5
Labels: feature

#133 Add Mantine simple header component
  templates/croct/ui/component/navbar/template.json5
  templates/mantine/component/header-simple/README.md
  templates/mantine/component/header-simple/code/components/HeaderSimple/index.module.css
  templates/mantine/component/header-simple/code/components/HeaderSimple/index.tsx
  templates/mantine/component/header-simple/code/page/nextjs/index.tsx
  templates/mantine/component/header-simple/code/page/nextjs/page.tsx
  templates/mantine/component/header-simple/code/page/react/page.tsx
  templates/mantine/component/header-simple/configuration/header-simple-content.en.json
  templates/mantine/component/header-simple/configuration/header-simple-schema.json
  templates/mantine/component/header-simple/extension.json5
  templates/mantine/component/header-simple/template.json5
  templates/material-ui/block/navbar/template.json5
Labels: feature

#123 Add sign-up form template from Material UI
  templates/croct/ui/component/demo-request-form/template.json5
  templates/material-ui/block/sign-up-form/README.md
  templates/material-ui/block/sign-up-form/code/components/CustomIcons.tsx
  templates/material-ui/block/sign-up-form/code/components/SignUpCard.tsx
  templates/material-ui/block/sign-up-form/code/components/SignUpSection.tsx
  templates/material-ui/block/sign-up-form/code/page/nextjs/index.tsx
  templates/material-ui/block/sign-up-form/code/page/nextjs/page.tsx
  templates/material-ui/block/sign-up-form/code/page/react/page.tsx
  templates/material-ui/block/sign-up-form/configuration/form-schema.json
  templates/material-ui/block/sign-up-form/configuration/sign-up-form-content.en.json
  templates/material-ui/block/sign-up-form/cover.png
  templates/material-ui/block/sign-up-form/extension.json5
  templates/material-ui/block/sign-up-form/template.json5
  templates/npm/react-phone-number-input/template.json5
Labels: feature

#137 Update links
  templates/croct/integration/sanity/code/nextjs/app/page.tsx
  templates/croct/starter/nextjs/README.md
  templates/croct/starter/nextjs/configuration/13/next-homepage-content.en.json
Labels: enhancement
