Repository croct-tech/templates, pull requests merged in 2025-07, with the labels that each got.

#136 Add Mantine features title template
  templates/mantine/block/features-title/README.md
  templates/mantine/block/features-title/code/components/FeaturesTitle/index.module.css
  templates/mantine/block/features-title/code/components/FeaturesTitle/index.tsx
  templates/mantine/block/features-title/code/page/nextjs/index.tsx
  templates/mantine/block/features-title/code/page/nextjs/page.tsx
  templates/mantine/block/features-title/code/page/react/page.tsx
  templates/mantine/block/features-title/configuration/features-title-content.en.json
  templates/mantine/block/features-title/configuration/features-title-schema.json
  templates/mantine/block/features-title/cover.png
  templates/mantine/block/features-title/extension.json5
  templates/mantine/block/features-title/template.json5
Labels: feature

#147 Add link to Strapi official integration guide
  templates/croct/integration/strapi-ab-testing/README.md
  templates/croct/integration/strapi-personalization/README.md
  templates/croct/integration/strapi/README.md
Labels: maintenance

#148 Standardize LinkButton and TemplateCanvas button labels
  templates/croct/integration/sanity-ab-testing/extension.json5
  templates/croct/integration/sanity-personalization/extension.json5
  templates/croct/integration/sanity/code/nextjs/app/page.tsx
  templates/croct/integration/strapi-ab-testing/extension.json5
  templates/croct/integration/strapi-personalization/extension.json5
  templates/croct/integration/strapi/code/page.tsx
  templates/croct/starter/nextjs/code/page/13/css/index.js
  templates/croct/starter/nextjs/code/page/13/css/index.tsx
  templates/croct/starter/nextjs/code/page/13/css/page.js
  templates/croct/starter/nextjs/code/page/13/tailwind/index.js
  templates/croct/starter/nextjs/code/page/13/tailwind/index.tsx
  templates/croct/starter/nextjs/code/page/13/tailwind/page.js
  templates/croct/starter/nextjs/code/page/14/css/index.js
  templates/croct/starter/nextjs/code/page/14/css/index.tsx
  templates/croct/starter/nextjs/code/page/14/css/page.js
  templates/croct/starter/nextjs/code/page/14/tailwind/index.js
  templates/croct/starter/nextjs/code/page/14/tailwind/index.tsx
  templates/croct/starter/nextjs/code/page/14/tailwind/page.js
  templates/croct/starter/nextjs/code/page/15/css/index.js
  templates/croct/starter/nextjs/code/page/15/css/index.tsx
  templates/croct/starter/nextjs/code/page/15/css/page.js
  templates/croct/starter/nextjs/code/page/15/tailwind/index.js
  templates/croct/starter/nextjs/code/page/15/tailwind/index.tsx
  templates/croct/starter/nextjs/code/page/15/tailwind/page.js
  templates/croct/ui/block/carousel-section/code/page/nextjs/index.tsx
  templates/croct/ui/block/carousel-section/code/page/nextjs/page.tsx
  templates/croct/ui/block/carousel-section/code/page/react/page.tsx
  templates/material-ui/block/sign-in-side/code/page/nextjs/index.tsx
  templates/material-ui/block/sign-in-side/code/page/nextjs/page.tsx
  templates/material-ui/block/sign-in-side/code/page/react/page.tsx
  templates/material-ui/block/sign-up-form/code/page/nextjs/index.tsx
  templates/material-ui/block/sign-up-form/code/page/nextjs/page.tsx
  templates/material-ui/block/sign-up-form/code/page/react/page.tsx
  templates/material-ui/block/sign-up-side/code/page/nextjs/index.tsx
  templates/material-ui/block/sign-up-side/code/page/nextjs/page.tsx
  templates/material-ui/block/sign-up-side/code/page/react/page.tsx
  templates/material-ui/template/marketing-page/code/page/nextjs/index.tsx
  templates/material-ui/template/marketing-page/code/page/nextjs/page.tsx
  templates/material-ui/template/marketing-page/code/page/react/page.tsx
  templates/shadcn-ui/block/pricing-page/code/page/nextjs/index.tsx
  templates/shadcn-ui/block/pricing-page/code/page/nextjs/page.tsx
  templates/shadcn-ui/block/pricing-page/code/page/react/page.tsx
Labels: maintenance

#152 Fix Mantine broken templates
  templates/mantine/block/features-title/code/components/FeaturesTitle/index.tsx
  templates/mantine/block/hero-content-left/code/components/HeroContentLeft/index.tsx
  templates/mantine/component/carousel-card/code/components/CarouselCard/index.tsx
  templates/mantine/component/image-action-banner/code/components/ImageActionBanner/index.tsx
Labels: bug

#154 Adjust shadcn version
  templates/croct/starter/shadcn-ui/template.json5
  templates/shadcn-ui/component/template.json5
Labels: bug

#157 Add Croct preview url
  templates/croct/starter/nextjs/template.json5
  templates/croct/ui/block/carousel-section/template.json5
  templates/croct/ui/component/announcement-bar/template.json5
  templates/npm/react-phone-number-input/template.json5
  templates/npm/swiper/react/template.json5
  templates/shadcn-ui/block/pricing-page/template.json5
Labels: feature
