Repository croct-tech/templates, pull requests merged in 2025-05, with the labels that each got.

#48 Update cover of use case templates
  templates/croct/experience/e-commerce/cart/cover.png
  templates/croct/experience/e-commerce/instagram-campaign/cover.png
  templates/croct/experience/e-commerce/interest/cover.png
  templates/croct/experience/e-commerce/landing-page/cover.png
  templates/croct/experience/e-commerce/location/cover.png
  templates/croct/experience/e-commerce/marketing-campaign/cover.png
  templates/croct/experience/e-commerce/search-campaign/cover.png
  templates/croct/experience/saas/customer/cover.png
  templates/croct/experience/saas/linkedin-campaign/cover.png
  templates/croct/experience/saas/search-campaign/cover.png
  templates/croct/experiment/segmented/cover.png
Labels: maintenance

#50 Add croct project template
  templates/croct/project/README.md
  templates/croct/project/cover.png
  templates/croct/project/template.json5
Labels: feature

#52 Fix template issues
  templates/croct/project/README.md
  templates/croct/project/template.json5
  templates/magic-ui/ui/component/template.json5
  templates/nextjs/croct/README.md
  templates/nextjs/croct/template.json5
  templates/nextjs/project/README.md
  templates/shadcn-ui/croct/README.md
  templates/shadcn-ui/croct/template.json5
  templates/shadcn-ui/project/README.md
  templates/shadcn-ui/ui/block/pricing-page/template.json5
Labels: maintenance

#54 Fix variable reference
  templates/croct/project/template.json5
Labels: bug

#55 Remove non-existing option
  templates/croct/project/template.json5
Labels: bug

#56 Add workflow for mirroring template files to CDN
  .github/workflows/mirror-files.yaml
  .github/workflows/publish-templates.yaml
  bin/cli.ts
  package.json
Labels: feature

#57 Add new images to use case templates
  templates/croct/experience/e-commerce/cart/README.md
  templates/croct/experience/e-commerce/cart/cover.png
  templates/croct/experience/e-commerce/cart/intro-illustration.png
  templates/croct/experience/e-commerce/instagram-campaign/README.md
  templates/croct/experience/e-commerce/instagram-campaign/intro-illustration.png
  templates/croct/experience/e-commerce/interest/README.md
  templates/croct/experience/e-commerce/interest/intro-illustration.png
  templates/croct/experience/e-commerce/landing-page/README.md
  templates/croct/experience/e-commerce/landing-page/intro-illustration.png
  templates/croct/experience/e-commerce/location/README.md
  templates/croct/experience/e-commerce/location/cover.png
  templates/croct/experience/e-commerce/location/intro-illustration.png
  templates/croct/experience/e-commerce/marketing-campaign/README.md
  templates/croct/experience/e-commerce/marketing-campaign/intro-illustration.png
  templates/croct/experience/e-commerce/search-campaign/README.md
  templates/croct/experience/e-commerce/search-campaign/intro-illustration.png
  templates/croct/experience/saas/abm-campaign/README.md
  templates/croct/experience/saas/abm-campaign/intro-illustration.png
  templates/croct/experience/saas/customer/README.md
  templates/croct/experience/saas/customer/intro-illustration.png
  templates/croct/experience/saas/interest/README.md
  templates/croct/experience/saas/interest/intro-illustration.png
  templates/croct/experience/saas/landing-page/README.md
  templates/croct/experience/saas/landing-page/intro-illustration.png
  templates/croct/experience/saas/linkedin-campaign/README.md
  templates/croct/experience/saas/linkedin-campaign/intro-illustration.png
  templates/croct/experience/saas/marketing-campaign/README.md
  templates/croct/experience/saas/marketing-campaign/intro-illustration.png
  templates/croct/experience/saas/search-campaign/README.md
  templates/croct/experience/saas/search-campaign/intro-illustration.png
  templates/croct/experiment/all-users/README.md
  templates/croct/experiment/all-users/cover.png
  templates/croct/experiment/segmented/README.md
  templates/croct/experiment/segmented/cover.png
Labels: maintenance

#59 Fix formatting
  templates/croct/ui/block/announcement-bar/template.json5
  templates/croct/ui/block/cards-section/template.json5
  templates/croct/ui/block/carousel-section/template.json5
  templates/croct/ui/block/faq-section/template.json5
  templates/croct/ui/block/hero-section/template.json5
  templates/croct/ui/block/logo-cloud/template.json5
  templates/croct/ui/block/product-cards-section/template.json5
  templates/croct/ui/block/testimonial-section/template.json5
  templates/croct/ui/component/callout/template.json5
  templates/croct/ui/component/demo-request-form/template.json5
  templates/croct/ui/component/image-comparison-slider/template.json5
  templates/croct/ui/component/modal-dialog/template.json5
  templates/croct/ui/component/navbar/template.json5
  templates/croct/ui/component/newsletter-form/template.json5
  templates/croct/ui/component/video-player/template.json5
Labels: maintenance

#60 Add code style checks
  bin/cli.ts
  package.json
  templates/croct/experience/e-commerce/cart/template.json5
  templates/croct/experience/e-commerce/instagram-campaign/template.json5
  templates/croct/experience/e-commerce/interest/template.json5
  templates/croct/experience/e-commerce/landing-page/template.json5
  templates/croct/experience/e-commerce/location/template.json5
  templates/croct/experience/e-commerce/marketing-campaign/template.json5
  templates/croct/experience/e-commerce/search-campaign/template.json5
  templates/croct/experience/saas/abm-campaign/template.json5
  templates/croct/experience/saas/customer/template.json5
  templates/croct/experience/saas/interest/template.json5
  templates/croct/experience/saas/landing-page/template.json5
  templates/croct/experience/saas/linkedin-campaign/template.json5
  templates/croct/experience/saas/marketing-campaign/template.json5
  templates/croct/experience/saas/search-campaign/template.json5
  templates/croct/experiment/all-users/template.json5
  templates/croct/experiment/segmented/template.json5
  templates/croct/project/template.json5
  templates/croct/ui/block/announcement-bar/template.json5
  templates/croct/ui/block/cards-section/template.json5
  templates/croct/ui/block/carousel-section/template.json5
  templates/croct/ui/block/faq-section/template.json5
  templates/croct/ui/block/hero-section/template.json5
  templates/croct/ui/block/logo-cloud/template.json5
  templates/croct/ui/block/product-cards-section/template.json5
  templates/croct/ui/block/testimonial-section/template.json5
  templates/croct/ui/component/callout/template.json5
  templates/croct/ui/component/demo-request-form/template.json5
  templates/croct/ui/component/image-comparison-slider/template.json5
  templates/croct/ui/component/modal-dialog/template.json5
  templates/croct/ui/component/navbar/template.json5
  templates/croct/ui/component/newsletter-form/template.json5
  templates/croct/ui/component/video-player/template.json5
  templates/croct/utils/example-launcher/template.json5
  templates/croct/utils/filename-generator/template.json5
  templates/magic-ui/ui/animated-list/template.json5
  templates/magic-ui/ui/avatar-circles/template.json5
  templates/magic-ui/ui/bento-grid/template.json5
  templates/magic-ui/ui/code-comparison/template.json5
  templates/magic-ui/ui/component/template.json5
  templates/magic-ui/ui/dock/template.json5
  templates/magic-ui/ui/globe/template.json5
  templates/magic-ui/ui/hero-video-dialog/template.json5
  templates/magic-ui/ui/icon-cloud/template.json5
  templates/magic-ui/ui/lens/template.json5
  templates/magic-ui/ui/marquee/template.json5
  templates/magic-ui/ui/orbiting-circles/template.json5
  templates/magic-ui/ui/script-copy-btn/template.json5
  templates/magic-ui/ui/terminal/template.json5
  templates/magic-ui/ui/tweet-card/template.json5
  templates/nextjs/croct/template.json5
  templates/nextjs/project/template.json5
  templates/shadcn-ui/croct/template.json5
  templates/shadcn-ui/project/template.json5
  templates/shadcn-ui/ui/block/pricing-page/template.json5
  templates/shadcn-ui/ui/component/template.json5
Labels: maintenance

#58 Add template for Swiper
  templates/croct/ui/block/carousel-section/README.md
  templates/croct/ui/block/carousel-section/code/components/carousel.module.css
  templates/croct/ui/block/carousel-section/code/page/page.module.css
  templates/croct/ui/block/carousel-section/template.json5
  templates/npm/swiper/react/README.md
  templates/npm/swiper/react/code/components/carousel.tsx
  templates/npm/swiper/react/cover.png
  templates/npm/swiper/react/extension.json5
  templates/npm/swiper/react/template.json5
  templates/npm/swiper/template.json5
Labels: feature

#62 Mixed template fixes
  templates/croct/experience/e-commerce/cart/intro-illustration.png
  templates/croct/experience/e-commerce/cart/template.json5
  templates/croct/experience/e-commerce/instagram-campaign/intro-illustration.png
  templates/croct/experience/e-commerce/instagram-campaign/template.json5
  templates/croct/experience/e-commerce/interest/intro-illustration.png
  templates/croct/experience/e-commerce/interest/template.json5
  templates/croct/experience/e-commerce/landing-page/intro-illustration.png
  templates/croct/experience/e-commerce/landing-page/template.json5
  templates/croct/experience/e-commerce/location/intro-illustration.png
  templates/croct/experience/e-commerce/location/template.json5
  templates/croct/experience/e-commerce/marketing-campaign/intro-illustration.png
  templates/croct/experience/e-commerce/marketing-campaign/template.json5
  templates/croct/experience/e-commerce/search-campaign/intro-illustration.png
  templates/croct/experience/e-commerce/search-campaign/template.json5
  templates/croct/experience/saas/abm-campaign/intro-illustration.png
  templates/croct/experience/saas/abm-campaign/template.json5
  templates/croct/experience/saas/customer/intro-illustration.png
  templates/croct/experience/saas/customer/template.json5
  templates/croct/experience/saas/interest/intro-illustration.png
  templates/croct/experience/saas/interest/template.json5
  templates/croct/experience/saas/landing-page/intro-illustration.png
  templates/croct/experience/saas/landing-page/template.json5
  templates/croct/experience/saas/linkedin-campaign/intro-illustration.png
  templates/croct/experience/saas/linkedin-campaign/template.json5
  templates/croct/experience/saas/marketing-campaign/intro-illustration.png
  templates/croct/experience/saas/marketing-campaign/template.json5
  templates/croct/experience/saas/search-campaign/intro-illustration.png
  templates/croct/experience/saas/search-campaign/template.json5
  templates/croct/experiment/all-users/template.json5
  templates/croct/experiment/segmented/template.json5
  templates/croct/ui/block/carousel-section/README.md
  templates/croct/ui/block/carousel-section/cover.png
  templates/croct/ui/block/carousel-section/template.json5
  templates/magic-ui/ui/animated-list/README.md
  templates/magic-ui/ui/avatar-circles/README.md
  templates/magic-ui/ui/bento-grid/README.md
  templates/magic-ui/ui/code-comparison/README.md
  templates/magic-ui/ui/component/README.md
  templates/magic-ui/ui/dock/README.md
  templates/magic-ui/ui/globe/README.md
  templates/magic-ui/ui/hero-video-dialog/README.md
  templates/magic-ui/ui/icon-cloud/README.md
  templates/magic-ui/ui/lens/README.md
  templates/magic-ui/ui/marquee/README.md
  templates/magic-ui/ui/orbiting-circles/README.md
  templates/magic-ui/ui/script-copy-btn/README.md
  templates/magic-ui/ui/terminal/README.md
  templates/magic-ui/ui/tweet-card/README.md
  templates/nextjs/croct/README.md
  templates/npm/swiper/react/README.md
  templates/npm/swiper/react/cover.png
  templates/shadcn-ui/ui/block/pricing-page/README.md
Labels: maintenance

#42 Add code to the announcement bar template
  templates/croct/ui/block/announcement-bar/README.md
  templates/croct/ui/block/announcement-bar/configuration/announcement-bar-content.en.json
  templates/croct/ui/block/announcement-bar/configuration/announcement-bar-schema.json
  templates/croct/ui/block/announcement-bar/cover.png
  templates/croct/ui/block/announcement-bar/template.json5
  templates/croct/ui/component/announcement-bar/README.md
  templates/croct/ui/component/announcement-bar/code/components/announcement-bar.module.css
  templates/croct/ui/component/announcement-bar/code/components/announcement-bar.tsx
  templates/croct/ui/component/announcement-bar/code/lib/nextjs/markdown.tsx
  templates/croct/ui/component/announcement-bar/code/lib/react/markdown.tsx
  templates/croct/ui/component/announcement-bar/code/page/content.module.css
  templates/croct/ui/component/announcement-bar/code/page/content.tsx
  templates/croct/ui/component/announcement-bar/code/page/nextjs/index.tsx
  templates/croct/ui/component/announcement-bar/code/page/nextjs/page.tsx
  templates/croct/ui/component/announcement-bar/code/page/react/page.tsx
  templates/croct/ui/component/announcement-bar/configuration/announcement-bar-content.en.json
  templates/croct/ui/component/announcement-bar/configuration/announcement-bar-schema.json
  templates/croct/ui/component/announcement-bar/cover.png
  templates/croct/ui/component/announcement-bar/template.json5
Labels: enhancement

#64 Fix mixed issues
  templates/croct/ui/block/carousel-section/code/components/header.tsx
  templates/croct/ui/block/carousel-section/code/page/nextjs/index.tsx
  templates/croct/ui/block/carousel-section/code/page/nextjs/page.tsx
  templates/croct/ui/block/carousel-section/code/page/react/page.tsx
  templates/croct/ui/block/carousel-section/template.json5
  templates/croct/ui/component/announcement-bar/code/components/announcement-bar.tsx
  templates/croct/ui/component/announcement-bar/code/lib/nextjs/markdown.tsx
  templates/croct/ui/component/announcement-bar/code/lib/react/markdown.tsx
  templates/croct/ui/component/announcement-bar/code/page/content.tsx
  templates/croct/ui/component/announcement-bar/code/page/nextjs/index.tsx
  templates/croct/ui/component/announcement-bar/code/page/nextjs/page.tsx
  templates/croct/ui/component/announcement-bar/code/page/react/page.tsx
  templates/croct/ui/component/announcement-bar/template.json5
  templates/magic-ui/ui/animated-list/code/components/notification-list.tsx
  templates/magic-ui/ui/avatar-circles/code/components/avatar-stack.tsx
  templates/magic-ui/ui/bento-grid/code/components/feature-grid.tsx
  templates/magic-ui/ui/code-comparison/code/components/code-diff-pane.tsx
  templates/magic-ui/ui/component/template.json5
  templates/magic-ui/ui/dock/code/components/dock-menu.tsx
  templates/magic-ui/ui/globe/code/components/global-presence.tsx
  templates/magic-ui/ui/hero-video-dialog/code/components/hero-video-player.tsx
  templates/magic-ui/ui/hero-video-dialog/code/page/nextjs/index.tsx
  templates/magic-ui/ui/icon-cloud/code/components/icon-cloud-demo.tsx
  templates/magic-ui/ui/lens/code/components/lens-card.tsx
  templates/magic-ui/ui/marquee/code/components/review-card.tsx
  templates/magic-ui/ui/marquee/code/components/review-list.tsx
  templates/magic-ui/ui/orbiting-circles/code/components/orbiting-icons.tsx
  templates/magic-ui/ui/script-copy-btn/code/components/copy-command-block.tsx
  templates/magic-ui/ui/tweet-card/code/components/client/tweet.tsx
  templates/magic-ui/ui/tweet-card/code/components/server/tweet.tsx
  templates/nextjs/croct/code/lib/markdown.tsx
  templates/nextjs/croct/code/page/13/css/index.tsx
  templates/nextjs/croct/code/page/13/css/page.js
  templates/nextjs/croct/code/page/13/tailwind/index.tsx
  templates/nextjs/croct/code/page/13/tailwind/page.js
  templates/nextjs/croct/code/page/14/css/index.tsx
  templates/nextjs/croct/code/page/14/css/page.js
  templates/nextjs/croct/code/page/14/tailwind/index.tsx
  templates/nextjs/croct/code/page/14/tailwind/page.js
  templates/nextjs/croct/code/page/15/css/index.js
  templates/nextjs/croct/code/page/15/css/index.tsx
  templates/nextjs/croct/code/page/15/css/page.js
  templates/nextjs/croct/code/page/15/tailwind/index.tsx
  templates/nextjs/croct/code/page/15/tailwind/page.js
  templates/nextjs/croct/template.json5
  templates/nextjs/project/template.json5
  templates/npm/swiper/react/code/components/carousel.tsx
  templates/shadcn-ui/ui/block/pricing-page/code/components/pricing-section.tsx
  templates/shadcn-ui/ui/block/pricing-page/template.json5
Labels: maintenance

#65 Update docs URLs
  templates/croct/experience/e-commerce/cart/README.md
  templates/croct/experience/e-commerce/instagram-campaign/README.md
  templates/croct/experience/e-commerce/interest/README.md
  templates/croct/experience/e-commerce/landing-page/README.md
  templates/croct/experience/e-commerce/location/README.md
  templates/croct/experience/e-commerce/marketing-campaign/README.md
  templates/croct/experience/e-commerce/search-campaign/README.md
  templates/croct/experience/saas/abm-campaign/README.md
  templates/croct/experience/saas/customer/README.md
  templates/croct/experience/saas/interest/README.md
  templates/croct/experience/saas/landing-page/README.md
  templates/croct/experience/saas/linkedin-campaign/README.md
  templates/croct/experience/saas/marketing-campaign/README.md
  templates/croct/experience/saas/search-campaign/README.md
Labels: maintenance

#63 Add a template for location-based messaging
  bin/cli.ts
  templates/croct/experience/e-commerce/location/template.json5
  templates/croct/location/geomarketing/README.md
  templates/croct/location/geomarketing/code/page/nextjs/index.tsx
  templates/croct/location/geomarketing/code/page/nextjs/page.tsx
  templates/croct/location/geomarketing/code/page/react/page.tsx
  templates/croct/location/geomarketing/configuration/announcement-bar-content.en.json
  templates/croct/location/geomarketing/configuration/announcement-bar-dynamic-content.en.json
  templates/croct/location/geomarketing/configuration/announcement-bar-static-content.en.json
  templates/croct/location/geomarketing/cover.png
  templates/croct/location/geomarketing/extension.json5
  templates/croct/location/geomarketing/template.json5
  templates/croct/ui/block/carousel-section/README.md
  templates/croct/ui/component/announcement-bar/README.md
  templates/croct/ui/component/announcement-bar/code/page/react/page.tsx
  templates/croct/ui/component/announcement-bar/cover.png
  templates/croct/ui/component/announcement-bar/template.json5
  templates/npm/swiper/template.json5
Labels: feature

#67 Update Croct UI template covers
  templates/croct/ui/block/cards-section/cover.png
  templates/croct/ui/block/faq-section/cover.png
  templates/croct/ui/block/hero-section/cover.png
  templates/croct/ui/block/logo-cloud/cover.png
  templates/croct/ui/block/product-cards-section/cover.png
  templates/croct/ui/block/testimonial-section/cover.png
  templates/croct/ui/component/callout/cover.png
  templates/croct/ui/component/demo-request-form/cover.png
  templates/croct/ui/component/image-comparison-slider/cover.png
  templates/croct/ui/component/modal-dialog/cover.png
  templates/croct/ui/component/navbar/cover.png
  templates/croct/ui/component/newsletter-form/cover.png
  templates/croct/ui/component/video-player/cover.png
Labels: maintenance

#66 React phone number input
  bin/cli.ts
  templates/croct/ui/component/demo-request-form/template.json5
  templates/croct/ui/component/newsletter-form/template.json5
  templates/npm/react-phone-number-input/README.md
  templates/npm/react-phone-number-input/code/components/phone-input.tsx
  templates/npm/react-phone-number-input/code/page/nextjs/index.tsx
  templates/npm/react-phone-number-input/code/page/nextjs/page.tsx
  templates/npm/react-phone-number-input/code/page/page.module.css
  templates/npm/react-phone-number-input/code/page/react/page.tsx
  templates/npm/react-phone-number-input/cover.png
  templates/npm/react-phone-number-input/template.json5
Labels: feature

#70 Move Next.js starter to Croct folder
  templates/croct/project/template.json5
  templates/croct/starter/nextjs/README.md
  templates/croct/starter/nextjs/asset/file.svg
  templates/croct/starter/nextjs/asset/globe.svg
  templates/croct/starter/nextjs/asset/next.svg
  templates/croct/starter/nextjs/asset/vercel.svg
  templates/croct/starter/nextjs/asset/window.svg
  templates/croct/starter/nextjs/code/lib/markdown.js
  templates/croct/starter/nextjs/code/lib/markdown.tsx
  templates/croct/starter/nextjs/code/page/13/css/index.js
  templates/croct/starter/nextjs/code/page/13/css/index.tsx
  templates/croct/starter/nextjs/code/page/13/css/page.js
  templates/croct/starter/nextjs/code/page/13/tailwind/index.js
  templates/croct/starter/nextjs/code/page/13/tailwind/index.tsx
  templates/croct/starter/nextjs/code/page/13/tailwind/page.js
  templates/croct/starter/nextjs/code/page/14/css/index.js
  templates/croct/starter/nextjs/code/page/14/css/index.tsx
  templates/croct/starter/nextjs/code/page/14/css/page.js
  templates/croct/starter/nextjs/code/page/14/tailwind/index.js
  templates/croct/starter/nextjs/code/page/14/tailwind/index.tsx
  templates/croct/starter/nextjs/code/page/14/tailwind/page.js
  templates/croct/starter/nextjs/code/page/15/css/index.js
  templates/croct/starter/nextjs/code/page/15/css/index.tsx
  templates/croct/starter/nextjs/code/page/15/css/page.js
  templates/croct/starter/nextjs/code/page/15/tailwind/index.js
  templates/croct/starter/nextjs/code/page/15/tailwind/index.tsx
  templates/croct/starter/nextjs/code/page/15/tailwind/page.js
  templates/croct/starter/nextjs/configuration/13/next-homepage-content.en.json
  templates/croct/starter/nextjs/configuration/13/next-starter-page-schema.json
  templates/croct/starter/nextjs/configuration/14/next-homepage-content.en.json
  templates/croct/starter/nextjs/configuration/14/next-starter-page-schema.json
  templates/croct/starter/nextjs/configuration/15/next-homepage-content.en.json
  templates/croct/starter/nextjs/configuration/15/next-starter-page-schema.json
  templates/croct/starter/nextjs/cover.png
  templates/croct/starter/nextjs/template.json5
  templates/croct/starter/shadcn-ui/README.md
  templates/croct/starter/shadcn-ui/cover.png
  templates/croct/starter/shadcn-ui/template.json5
  templates/magic-ui/ui/component/template.json5
  templates/shadcn-ui/project/template.json5
Labels: maintenance

#71 Fix template references
  templates/croct/starter/nextjs/template.json5
  templates/croct/starter/shadcn-ui/template.json5
Labels: bug

#72 Add default for verified flag
  bin/cli.ts
Labels: bug

#79 Add hero ui component
  templates/croct/starter/croct/template.json5
  templates/croct/starter/hero-ui/code/configuration/globals.css
  templates/croct/starter/hero-ui/template.json5
  templates/croct/starter/shadcn-ui/template.json5
  templates/croct/ui/block/carousel-section/README.md
  templates/croct/ui/component/announcement-bar/README.md
  templates/hero-ui/component/component/README.md
  templates/hero-ui/component/component/cover.png
  templates/hero-ui/component/component/template.json5
  templates/hero-ui/component/cookie-consent/README.md
  templates/hero-ui/component/cookie-consent/code/components/cookie-consent-demo.tsx
  templates/hero-ui/component/cookie-consent/code/components/cookie-consent.tsx
  templates/hero-ui/component/cookie-consent/code/page/nextjs/index.tsx
  templates/hero-ui/component/cookie-consent/code/page/nextjs/page.tsx
  templates/hero-ui/component/cookie-consent/code/page/react/page.tsx
  templates/hero-ui/component/cookie-consent/cover.png
  templates/hero-ui/component/cookie-consent/extension.json5
  templates/hero-ui/component/cookie-consent/template.json5
  templates/magic-ui/component/component/template.json5
  templates/shadcn-ui/block/pricing-page/template.json5
Labels: feature

#83 Update registry.json5
  templates/registry.json5
Labels: bug

#81 Refactor Magic UI components to use extensions
  templates/magic-ui/component/animated-list/configuration/animated-list-schema.json
  templates/magic-ui/component/animated-list/extension.json5
  templates/magic-ui/component/animated-list/template.json5
  templates/magic-ui/component/avatar-circles/configuration/avatar-circles-schema.json
  templates/magic-ui/component/avatar-circles/extension.json5
  templates/magic-ui/component/avatar-circles/template.json5
  templates/magic-ui/component/bento-grid/configuration/bento-grid-schema.json
  templates/magic-ui/component/bento-grid/extension.json5
  templates/magic-ui/component/bento-grid/template.json5
  templates/magic-ui/component/code-comparison/configuration/code-comparison-schema.json
  templates/magic-ui/component/code-comparison/extension.json5
  templates/magic-ui/component/code-comparison/template.json5
  templates/magic-ui/component/component/README.md
  templates/magic-ui/component/component/template.json5
  templates/magic-ui/component/dock/configuration/dock-schema.json
  templates/magic-ui/component/dock/extension.json5
  templates/magic-ui/component/dock/template.json5
  templates/magic-ui/component/globe/configuration/globe-schema.json
  templates/magic-ui/component/globe/extension.json5
  templates/magic-ui/component/globe/template.json5
  templates/magic-ui/component/hero-video-dialog/extension.json5
  templates/magic-ui/component/hero-video-dialog/template.json5
  templates/magic-ui/component/icon-cloud/configuration/icon-cloud-schema.json
  templates/magic-ui/component/icon-cloud/extension.json5
  templates/magic-ui/component/icon-cloud/template.json5
  templates/magic-ui/component/lens/configuration/lens-schema.json
  templates/magic-ui/component/lens/extension.json5
  templates/magic-ui/component/lens/template.json5
  templates/magic-ui/component/marquee/configuration/marquee-schema.json
  templates/magic-ui/component/marquee/extension.json5
  templates/magic-ui/component/marquee/template.json5
  templates/magic-ui/component/orbiting-circles/configuration/orbiting-circles-schema.json
  templates/magic-ui/component/orbiting-circles/extension.json5
  templates/magic-ui/component/orbiting-circles/template.json5
  templates/magic-ui/component/script-copy-btn/configuration/script-copy-btn-schema.json
  templates/magic-ui/component/script-copy-btn/extension.json5
  templates/magic-ui/component/script-copy-btn/template.json5
  templates/magic-ui/component/terminal/configuration/terminal-schema.json
  templates/magic-ui/component/terminal/extension.json5
  templates/magic-ui/component/terminal/template.json5
  templates/magic-ui/component/tweet-card/configuration/tweet-card-schema.json
  templates/magic-ui/component/tweet-card/extension.json5
  templates/magic-ui/component/tweet-card/template.json5
Labels: maintenance

#78 Add Tailwind templates
  templates/registry.json5
  templates/tailwind/block/banner/README.md
  templates/tailwind/block/banner/cover.png
  templates/tailwind/block/banner/template.json5
  templates/tailwind/block/cta-section/README.md
  templates/tailwind/block/cta-section/cover.png
  templates/tailwind/block/cta-section/template.json5
  templates/tailwind/block/feature-section/README.md
  templates/tailwind/block/feature-section/cover.png
  templates/tailwind/block/feature-section/template.json5
  templates/tailwind/block/header-section/README.md
  templates/tailwind/block/header-section/cover.png
  templates/tailwind/block/header-section/template.json5
  templates/tailwind/block/hero-section/README.md
  templates/tailwind/block/hero-section/cover.png
  templates/tailwind/block/hero-section/template.json5
  templates/tailwind/block/logo-cloud/README.md
  templates/tailwind/block/logo-cloud/cover.png
  templates/tailwind/block/logo-cloud/template.json5
  templates/tailwind/block/pricing-section/README.md
  templates/tailwind/block/pricing-section/cover.png
  templates/tailwind/block/pricing-section/template.json5
  templates/tailwind/block/testimonial-section/README.md
  templates/tailwind/block/testimonial-section/cover.png
  templates/tailwind/block/testimonial-section/template.json5
Labels: enhancement

#84 Improve Hero UI template
  templates/hero-ui/component/component/README.md
  templates/hero-ui/component/component/template.json5
  templates/hero-ui/component/cookie-consent/code/components/cookie-consent-demo.tsx
  templates/hero-ui/component/cookie-consent/code/components/cookie-consent.tsx
  templates/hero-ui/component/cookie-consent/code/page/nextjs/index.tsx
  templates/hero-ui/component/cookie-consent/code/page/nextjs/page.tsx
  templates/hero-ui/component/cookie-consent/code/page/react/page.tsx
  templates/hero-ui/component/cookie-consent/code/utils/markdown.tsx
  templates/hero-ui/component/cookie-consent/configuration/consent-banner-schema.json
  templates/hero-ui/component/cookie-consent/configuration/consent-banner.en.json
  templates/hero-ui/component/cookie-consent/extension.json5
  templates/hero-ui/component/cookie-consent/template.json5
  templates/magic-ui/component/component/README.md
Labels: feature

#87 Add new validations
  bin/cli.ts
  templates/croct/location/geomarketing/configuration/announcement-bar-static-content.en.json
  templates/croct/ui/component/image-comparison-slider/configuration/image-comparison-slider-content.en.json
  templates/hero-ui/component/cookie-consent/extension.json5
  templates/magic-ui/component/animated-list/extension.json5
  templates/magic-ui/component/avatar-circles/extension.json5
  templates/magic-ui/component/bento-grid/extension.json5
  templates/magic-ui/component/code-comparison/extension.json5
  templates/magic-ui/component/dock/extension.json5
  templates/magic-ui/component/globe/extension.json5
  templates/magic-ui/component/hero-video-dialog/extension.json5
  templates/magic-ui/component/icon-cloud/extension.json5
  templates/magic-ui/component/lens/extension.json5
  templates/magic-ui/component/marquee/extension.json5
  templates/magic-ui/component/orbiting-circles/extension.json5
  templates/magic-ui/component/script-copy-btn/extension.json5
  templates/magic-ui/component/terminal/configuration/terminal-schema.json
  templates/magic-ui/component/terminal/extension.json5
  templates/magic-ui/component/tweet-card/extension.json5
  templates/npm/swiper/react/extension.json5
  templates/shadcn-ui/block/pricing-page/configuration/plan-card-component.json
  templates/shadcn-ui/block/pricing-page/configuration/pricing-section-component.json
  templates/shadcn-ui/block/pricing-page/configuration/pricing-section-content.en.json
  templates/shadcn-ui/block/pricing-page/template.json5
Labels: enhancement

#88 Add Tailwind hero template
  templates/tailwind/block/block/README.md
  templates/tailwind/block/block/cover.png
  templates/tailwind/block/block/template.json5
  templates/tailwind/block/hero-section/README.md
  templates/tailwind/block/hero-section/code/components/hero-demo.tsx
  templates/tailwind/block/hero-section/code/components/hero-section.tsx
  templates/tailwind/block/hero-section/code/page/nextjs/index.tsx
  templates/tailwind/block/hero-section/code/page/nextjs/page.tsx
  templates/tailwind/block/hero-section/code/page/react/page.tsx
  templates/tailwind/block/hero-section/configuration/hero-section-content.en.json
  templates/tailwind/block/hero-section/configuration/hero-section-schema.json
  templates/tailwind/block/hero-section/extension.json5
  templates/tailwind/block/hero-section/template.json5
Labels: enhancement

#89 Add Tailwind CTA section template
  templates/tailwind/block/cta-section/README.md
  templates/tailwind/block/cta-section/code/components/cta-section.tsx
  templates/tailwind/block/cta-section/code/page/nextjs/index.tsx
  templates/tailwind/block/cta-section/code/page/nextjs/page.tsx
  templates/tailwind/block/cta-section/code/page/react/page.tsx
  templates/tailwind/block/cta-section/configuration/cta-section-content.en.json
  templates/tailwind/block/cta-section/configuration/cta-section-schema.json
  templates/tailwind/block/cta-section/extension.json5
  templates/tailwind/block/cta-section/template.json5
Labels: enhancement

#91 Add Material UI hero template
  templates/material-ui/block/block/README.md
  templates/material-ui/block/block/code/components/AppBar.tsx
  templates/material-ui/block/block/code/components/AppTheme.tsx
  templates/material-ui/block/block/code/components/ColorModeIconDropdown.tsx
  templates/material-ui/block/block/code/components/ColorModeSelect.tsx
  templates/material-ui/block/block/code/components/SitemarkIcon.tsx
  templates/material-ui/block/block/code/components/theme/dataDisplay.tsx
  templates/material-ui/block/block/code/components/theme/feedback.tsx
  templates/material-ui/block/block/code/components/theme/inputs.tsx
  templates/material-ui/block/block/code/components/theme/navigation.tsx
  templates/material-ui/block/block/code/components/theme/surfaces.ts
  templates/material-ui/block/block/code/components/theme/themePrimitives.ts
  templates/material-ui/block/block/cover.png
  templates/material-ui/block/block/template.json5
  templates/material-ui/block/hero-section/README.md
  templates/material-ui/block/hero-section/code/components/hero-demo.tsx
  templates/material-ui/block/hero-section/code/components/hero-section.tsx
  templates/material-ui/block/hero-section/code/page/nextjs/index.tsx
  templates/material-ui/block/hero-section/code/page/nextjs/page.tsx
  templates/material-ui/block/hero-section/code/page/react/page.tsx
  templates/material-ui/block/hero-section/code/utils/markdown.tsx
  templates/material-ui/block/hero-section/configuration/hero-section-content.en.json
  templates/material-ui/block/hero-section/configuration/hero-section-schema.json
  templates/material-ui/block/hero-section/extension.json5
  templates/material-ui/block/hero-section/template.json5
Labels: enhancement

#92 Tailwind and Material UI fixes
  templates/material-ui/block/faq-section/template.json5
  templates/material-ui/block/features-section/template.json5
  templates/material-ui/block/hero-section/template.json5
  templates/material-ui/block/highlights-section/template.json5
  templates/material-ui/block/logo-collection/template.json5
  templates/material-ui/block/navbar/template.json5
  templates/material-ui/block/pricing-section/template.json5
  templates/material-ui/block/testimonials-section/template.json5
  templates/tailwind/block/banner/template.json5
  templates/tailwind/block/cta-section/template.json5
  templates/tailwind/block/feature-section/template.json5
  templates/tailwind/block/header-section/template.json5
  templates/tailwind/block/hero-section/template.json5
  templates/tailwind/block/logo-cloud/template.json5
  templates/tailwind/block/pricing-section/template.json5
  templates/tailwind/block/testimonial-section/template.json5
Labels: maintenance

#94 Add Material UI features section template
  templates/croct/ui/block/cards-section/template.json5
  templates/material-ui/block/features-section/README.md
  templates/material-ui/block/features-section/code/components/features-demo.tsx
  templates/material-ui/block/features-section/code/components/features-section.tsx
  templates/material-ui/block/features-section/code/page/nextjs/index.tsx
  templates/material-ui/block/features-section/code/page/nextjs/page.tsx
  templates/material-ui/block/features-section/code/page/react/page.tsx
  templates/material-ui/block/features-section/configuration/features-section-content.en.json
  templates/material-ui/block/features-section/configuration/features-section-schema.json
  templates/material-ui/block/features-section/extension.json5
  templates/material-ui/block/features-section/template.json5
  templates/material-ui/block/highlights-section/template.json5
  templates/tailwind/block/feature-section/template.json5
Labels: enhancement

#93 Add Tailwind testimonial section template
  templates/tailwind/block/testimonial-section/README.md
  templates/tailwind/block/testimonial-section/code/components/testimonial-section.tsx
  templates/tailwind/block/testimonial-section/code/page/nextjs/index.tsx
  templates/tailwind/block/testimonial-section/code/page/nextjs/page.tsx
  templates/tailwind/block/testimonial-section/code/page/react/page.tsx
  templates/tailwind/block/testimonial-section/configuration/testimonial-section-content.en.json
  templates/tailwind/block/testimonial-section/configuration/testimonial-section-schema.json
  templates/tailwind/block/testimonial-section/extension.json5
  templates/tailwind/block/testimonial-section/template.json5
Labels: enhancement

#95 Add Tailwind logo cloud template
  templates/tailwind/block/logo-cloud/README.md
  templates/tailwind/block/logo-cloud/code/components/logo-cloud.tsx
  templates/tailwind/block/logo-cloud/code/page/nextjs/index.tsx
  templates/tailwind/block/logo-cloud/code/page/nextjs/page.tsx
  templates/tailwind/block/logo-cloud/code/page/react/page.tsx
  templates/tailwind/block/logo-cloud/configuration/logo-cloud-content.en.json
  templates/tailwind/block/logo-cloud/configuration/logo-cloud-schema.json
  templates/tailwind/block/logo-cloud/extension.json5
  templates/tailwind/block/logo-cloud/template.json5
Labels: enhancement

#75 Update CQL
  templates/croct/experience/e-commerce/location/README.md
  templates/croct/experience/e-commerce/location/template.json5
  templates/croct/location/geomarketing/configuration/announcement-bar-dynamic-content.en.json
  templates/croct/location/geomarketing/configuration/announcement-bar-static-content.en.json
  templates/npm/react-phone-number-input/code/page/nextjs/index.tsx
  templates/npm/react-phone-number-input/code/page/nextjs/page.tsx
  templates/npm/react-phone-number-input/code/page/react/page.tsx
Labels: maintenance

#104 Add Material UI testimonials section
  templates/material-ui/block/testimonials-section/README.md
  templates/material-ui/block/testimonials-section/code/components/testimonials-demo.tsx
  templates/material-ui/block/testimonials-section/code/components/testimonials-section.tsx
  templates/material-ui/block/testimonials-section/code/page/nextjs/index.tsx
  templates/material-ui/block/testimonials-section/code/page/nextjs/page.tsx
  templates/material-ui/block/testimonials-section/code/page/react/page.tsx
  templates/material-ui/block/testimonials-section/configuration/testimonials-section-content.en.json
  templates/material-ui/block/testimonials-section/configuration/testimonials-section-schema.json
  templates/material-ui/block/testimonials-section/extension.json5
  templates/material-ui/block/testimonials-section/template.json5
Labels: enhancement

#100 Add Material UI highlights section template
  templates/material-ui/block/highlights-section/README.md
  templates/material-ui/block/highlights-section/code/components/highlights-demo.tsx
  templates/material-ui/block/highlights-section/code/components/highlights-section.tsx
  templates/material-ui/block/highlights-section/code/page/nextjs/index.tsx
  templates/material-ui/block/highlights-section/code/page/nextjs/page.tsx
  templates/material-ui/block/highlights-section/code/page/react/page.tsx
  templates/material-ui/block/highlights-section/configuration/highlights-section-content.en.json
  templates/material-ui/block/highlights-section/configuration/highlights-section-schema.json
  templates/material-ui/block/highlights-section/extension.json5
  templates/material-ui/block/highlights-section/template.json5
Labels: enhancement

#108 Update action names
  templates/croct/starter/croct/template.json5
  templates/croct/starter/hero-ui/template.json5
  templates/croct/starter/nextjs/template.json5
  templates/croct/starter/shadcn-ui/template.json5
  templates/croct/utils/filename-generator/template.json5
  templates/material-ui/block/block/template.json5
  templates/shadcn-ui/component/template.json5
Labels: maintenance

#101 Mixed fixes
  templates/croct/location/geomarketing/cover.png
  templates/croct/ui/component/announcement-bar/cover.png
  templates/material-ui/block/faq-section/cover.png
  templates/material-ui/block/features-section/code/components/features-section.tsx
  templates/material-ui/block/features-section/configuration/features-section-schema.json
  templates/material-ui/block/logo-collection/cover.png
  templates/material-ui/block/navbar/cover.png
  templates/npm/react-phone-number-input/cover.png
  templates/npm/swiper/react/cover.png
Labels: maintenance
